name: Fedora

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:42

    steps:
    - name: Install image dependencies
      run: |
        dnf install -y curl git gcovr 
        curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -

    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Remove boost submodule (using system packages instead)
      run: |
        rm -rf external/boost
        git config --file .gitmodules --remove-section submodule.external/boost || true

    - name: install dependencies
      run: |
          dnf update -y
          dnf install -y \
            make \
            gcc \
            gcc-c++ \
            glibc-devel \
            gtk3-devel \
            webkit2gtk4.1-devel \
            gtk3 \
            webkit2gtk4.1 \
            pkgconf-pkg-config \
            boost-devel \
            boost-static

    - name: make
      run: make
