name: Fedora

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:42

    steps:
    - name: Install image dependencies
      run: |
        dnf install -y curl git gcovr 
        curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -

    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: install dependencies
      run: |
          dnf update -y
          dnf install -y \
            make \
            gcc \
            gcc-c++ \
            glibc-devel \
            gtk3-devel \
            webkit2gtk4.1-devel \
            gtk3 \
            webkit2gtk4.1 \
            pkgconf-pkg-config

    - name: Build Boost 1.90.0 from submodule
      run: |
        cd external/boost
        ./bootstrap.sh --prefix=/usr/local --with-libraries=program_options,json,system
        ./b2 install --prefix=/usr/local link=static runtime-link=shared threading=multi variant=release -j$(nproc)

    - name: make
      run: make
