name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install NSIS
      uses: repolevedavaj/install-nsis@v1.0.1
      with:
        nsis-version: '3.10'

    - name: Get and unzip WebView2
      run: |
        curl -L https://www.nuget.org/api/v2/package/Microsoft.Web.WebView2/1.0.3405.78 -o C:\webview2.nupkg
        mkdir C:\webview2
        tar -xf C:\webview2.nupkg -C C:\webview2
      
    - name: Download and build Boost
      run: |
        curl -L https://boostorg.jfrog.io/artifactory/main/release/1.82.0/source/boost_1_82_0.tar.gz -o C:\boost.tar.gz
        tar -xzf C:\boost.tar.gz -C C:\
        cd C:\boost_1_82_0
        .\bootstrap.bat
        .\b2 --with-program_options --with-json link=static runtime-link=shared threading=multi variant=release address-model=64 stage
        mkdir C:\boost_libs
        xcopy /Y stage\lib\*.lib C:\boost_libs\
      shell: cmd

        
    - name: Set Include
      run: |
        echo "INCLUDE=C:\webview2\build\native\include;C:\boost_1_82_0;${env:INCLUDE}" >> $env:GITHUB_ENV

    - name: Set Lib
      run: |
        echo "LIBPATH=C:\boost_libs;${env:LIBPATH}" >> $env:GITHUB_ENV
        dir C:\boost_libs

    - name: View vars
      run: |
        echo "INCLUDE = $env:INCLUDE"
        echo "LIBPATH = $env:LIBPATH"

    - name: make
      run: |
        git --version
        ls
        $boostLibs = (Get-ChildItem C:\boost_libs -Filter "*.lib" | Select-Object -First 2).FullName -join " "
        make LIBS="$boostLibs"
      working-directory: .
      shell: pwsh
