name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install NSIS
      uses: repolevedavaj/install-nsis@v1.0.1
      with:
        nsis-version: '3.10'

    - name: Get and unzip WebView2
      run: |
        curl -L https://www.nuget.org/api/v2/package/Microsoft.Web.WebView2/1.0.3405.78 -o C:\webview2.nupkg
        mkdir C:\webview2
        tar -xf C:\webview2.nupkg -C C:\webview2
      
    - name: Build Boost from submodule
      run: |
        cd external/boost
        git submodule update --init --recursive libs/process libs/json libs/program_options libs/system libs/config libs/core libs/asio libs/filesystem
        call bootstrap.bat
        b2 headers
        b2 --with-program_options --with-json link=static threading=multi variant=release address-model=64 stage
        if not exist ..\..\lib mkdir ..\..\lib
        xcopy /Y stage\lib\*.lib ..\..\lib\
      shell: cmd

        
    - name: Set Include
      run: |
        echo "INCLUDE=C:\webview2\build\native\include;${{ github.workspace }}\external\boost;${env:INCLUDE}" >> $env:GITHUB_ENV

    - name: Set Lib
      run: |
        echo "LIBPATH=${{ github.workspace }}\lib;${env:LIBPATH}" >> $env:GITHUB_ENV
        dir ${{ github.workspace }}\lib

    - name: View vars
      run: |
        echo "INCLUDE = $env:INCLUDE"
        echo "LIBPATH = $env:LIBPATH"

    - name: make
      run: |
        git --version
        ls
        $boostLibs = (Get-ChildItem lib -Filter "*.lib").FullName -join " "
        make LIBS="$boostLibs"
      working-directory: .
      shell: pwsh
